version: '2'
services:
    ciderhaus-app:
        image: ciderhaus
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ciderhaus-mysql:3306/ciderhaus?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ciderhaus-mysql:
        extends:
            file: mysql.yml
            service: ciderhaus-mysql
